-- Create Employees Table
CREATE TABLE employees (
    emp_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR2(50) NOT NULL,
    last_name     VARCHAR2(50) NOT NULL,
    email         VARCHAR2(100) UNIQUE NOT NULL,
    hire_date     DATE DEFAULT SYSDATE,
    department    VARCHAR2(50),
    status        VARCHAR2(20) DEFAULT 'Active'
);

-- Create Attendance Table
CREATE TABLE attendance (
    attendance_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id        NUMBER NOT NULL,
    attendance_date DATE NOT NULL,
    check_in_time   TIMESTAMP,
    check_out_time  TIMESTAMP,
    status          VARCHAR2(20), -- Present / Absent / Leave
    CONSTRAINT fk_emp_att FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
);

-- Create Timesheet Table
CREATE TABLE timesheets (
    timesheet_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id        NUMBER NOT NULL,
    week_start    DATE NOT NULL,
    week_end      DATE NOT NULL,
    total_hours   NUMBER(5,2),
    remarks       VARCHAR2(200),
    CONSTRAINT fk_emp_ts FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
);
